author: Jonathan Cohen, Samuel Nastase, Alexander Ku
bibtex_bibfiles:
- references.bib
copyright: '2025'
execute:
  allow_errors: true
  execute_notebooks: auto
html:
  baseurl: https://younesstrittmatter.github.io/NEU-PSY-MOL-502/
  use_repository_button: true
latex:
  latex_documents:
    targetname: book.tex
launch_buttons:
  colab_url: https://colab.research.google.com
  thebe: false
logo: logo.svg
parse:
  myst_substitutions:
    assets_url: https://younesstrittmatter.github.io/NEU-PSY-MOL-502/_static
    base_url: https://younesstrittmatter.github.io/NEU-PSY-MOL-502
    raw_data_url: https://github.com/younesStrittmatter/NEU-PSY-MOL-502/raw/refs/heads/main/data
    repo_url: https://github.com/younesStrittmatter/NEU-PSY-MOL-502
repository:
  branch: master
  path_to_book: _book_build
  url: https://github.com/younesStrittmatter/NEU-PSY-MOL-502
title: NEU-PSY-MOL-502
